"""init

Revision ID: 279c883f8874
Revises: 
Create Date: 2026-07-04 14:46:09.957843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '279c883f8874'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('chat_message',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='chat_role_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('agent_used', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_message_session_id'), 'chat_message', ['session_id'], unique=False)
    op.create_table('interview_session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_position', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.Enum('junior', 'mid', name='interview_difficulty_enum'), nullable=False),
    sa.Column('category', sa.Enum('algorithmic', 'system', 'behavioral', name='interview_category_enum'), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_session_user_id'), 'interview_session', ['user_id'], unique=False)
    op.create_table('skill_gap_report',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_position', sa.String(length=255), nullable=False),
    sa.Column('source_document_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'processing', 'completed', 'failed', name='processing_status_enum'), nullable=False),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_gap_report_user_id'), 'skill_gap_report', ['user_id'], unique=False)
    op.create_table('uploaded_document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('cv', 'linkedin_pdf', 'generated_cv', name='document_type_enum'), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parsed_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cv_score', sa.Integer(), nullable=True),
    sa.Column('cv_score_explanation', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('upload', 'generated', name='document_source_enum'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'completed', 'failed', name='processing_status_enum'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_document_document_type'), 'uploaded_document', ['document_type'], unique=False)
    op.create_index(op.f('ix_uploaded_document_user_id'), 'uploaded_document', ['user_id'], unique=False)
    op.create_table('user_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('github_username', sa.String(length=255), nullable=True),
    sa.Column('target_position', sa.String(length=255), nullable=True),
    sa.Column('target_company', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profile_user_id'), 'user_profile', ['user_id'], unique=True)
    op.create_table('cv_draft',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_document_id', sa.UUID(), nullable=True),
    sa.Column('form_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cv_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_text_tr', sa.Text(), nullable=True),
    sa.Column('generated_text_en', sa.Text(), nullable=True),
    sa.Column('user_edited_text', sa.Text(), nullable=True),
    sa.Column('output_language', sa.Enum('tr', 'en', 'both', name='output_language_enum'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'generated', 'exported', name='cv_draft_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_document_id'], ['uploaded_document.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cv_draft_user_id'), 'cv_draft', ['user_id'], unique=False)
    op.create_table('document_embedding',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['uploaded_document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roadmap',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skill_gap_report_id', sa.UUID(), nullable=False),
    sa.Column('weeks_total', sa.Integer(), nullable=True),
    sa.Column('weekly_hours', sa.Integer(), nullable=False),
    sa.Column('milestones', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'completed', 'failed', name='processing_status_enum'), nullable=False),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_gap_report_id'], ['skill_gap_report.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_user_id'), 'roadmap', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # --- RAG (ARCHITECTURE.md §4.3): HNSW cosine index + GIN metadata index ---
    # pgvector extension'ın mevcut olduğundan emin ol (app startup'ta da kontrol ediliyor,
    # ancak migration'ın bağımsız çalışabilmesi için burada da garanti altına alınır).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute(
        "CREATE INDEX ix_docemb_hnsw ON document_embedding "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    op.execute(
        "CREATE INDEX ix_docemb_metadata ON document_embedding "
        "USING gin (metadata jsonb_path_ops)"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_docemb_metadata")
    op.execute("DROP INDEX IF EXISTS ix_docemb_hnsw")
    op.drop_index(op.f('ix_roadmap_user_id'), table_name='roadmap')
    op.drop_table('roadmap')
    op.drop_table('document_embedding')
    op.drop_index(op.f('ix_cv_draft_user_id'), table_name='cv_draft')
    op.drop_table('cv_draft')
    op.drop_index(op.f('ix_user_profile_user_id'), table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_index(op.f('ix_uploaded_document_user_id'), table_name='uploaded_document')
    op.drop_index(op.f('ix_uploaded_document_document_type'), table_name='uploaded_document')
    op.drop_table('uploaded_document')
    op.drop_index(op.f('ix_skill_gap_report_user_id'), table_name='skill_gap_report')
    op.drop_table('skill_gap_report')
    op.drop_index(op.f('ix_interview_session_user_id'), table_name='interview_session')
    op.drop_table('interview_session')
    op.drop_index(op.f('ix_chat_message_session_id'), table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
